In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/exercise_1.csv')
df

i     xi     yi     zi
0    0  0.000  1.000  0.000
1    1  0.309  0.951  0.841
2    2  0.588  0.809  0.909
3    3  0.809  0.588  0.141
4    4  0.951  0.309 -0.757
5    5  1.000  0.000 -0.959
6    6  0.951 -0.309 -0.279
7    7  0.809 -0.588  0.657
8    8  0.588 -0.809  0.989
9    9  0.309 -0.951  0.412
10  10  0.000 -1.000 -0.544

In [4]:
[np.sum(arr) for arr in [df['xi'], df['yi'], df['zi']]]

[6.314, -3.3306690738754696e-16, 1.4100000000000001]

In [6]:
np.cov(df['xi'], df['yi'], ddof=0), np.cov(df['zi'], df['yi'], ddof=0), np.cov(df['xi'], df['zi'], ddof=0)

(array([[1.25088909e-01, 1.00929366e-17],
        [1.00929366e-17, 5.45474000e-01]]),
 array([[0.43806615, 0.03964991],
        [0.03964991, 0.545474  ]]),
 array([[ 0.12508891, -0.05498118],
        [-0.05498118,  0.43806615]]))