In [1]:
import numpy as np

In [1]:
99 - len(set([i for i in range(1, 101) for j in range(2, i) if i %j == 0]))

In [4]:
pnum = list(filter(lambda x:not [y for y in range(2,x) if x%y==0], range(100, 1, -1)))

<function __main__.<lambda>(x)>

In [45]:
for x in range(100, 1, -1):
    print(x, [y for y in range(2,x) if x%y==0], not [y for y in range(2,x) if x%y==0])

100 [2, 4, 5, 10, 20, 25, 50] False
99 [3, 9, 11, 33] False
98 [2, 7, 14, 49] False
97 [] True
96 [2, 3, 4, 6, 8, 12, 16, 24, 32, 48] False
95 [5, 19] False
94 [2, 47] False
93 [3, 31] False
92 [2, 4, 23, 46] False
91 [7, 13] False
90 [2, 3, 5, 6, 9, 10, 15, 18, 30, 45] False
89 [] True
88 [2, 4, 8, 11, 22, 44] False
87 [3, 29] False
86 [2, 43] False
85 [5, 17] False
84 [2, 3, 4, 6, 7, 12, 14, 21, 28, 42] False
83 [] True
82 [2, 41] False
81 [3, 9, 27] False
80 [2, 4, 5, 8, 10, 16, 20, 40] False
79 [] True
78 [2, 3, 6, 13, 26, 39] False
77 [7, 11] False
76 [2, 4, 19, 38] False
75 [3, 5, 15, 25] False
74 [2, 37] False
73 [] True
72 [2, 3, 4, 6, 8, 9, 12, 18, 24, 36] False
71 [] True
70 [2, 5, 7, 10, 14, 35] False
69 [3, 23] False
68 [2, 4, 17, 34] False
67 [] True
66 [2, 3, 6, 11, 22, 33] False
65 [5, 13] False
64 [2, 4, 8, 16, 32] False
63 [3, 7, 9, 21] False
62 [2, 31] False
61 [] True
60 [2, 3, 4, 5, 6, 10, 12, 15, 20, 30] False
59 [] True
58 [2, 29] False
57 [3, 19] False
56 [2, 4, 

In [8]:
!conda install -y -c pytorch pytorch

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/nakatani/.pyenv/versions/anaconda3-5.3.0/envs/m1

  added / updated specs:
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.11.0             |          py3.7_0        69.7 MB  pytorch
    ------------------------------------------------------------
                                           Total:        69.7 MB

The following NEW packages will be INSTALLED:

  libuv              pkgs/main/osx-64::libuv-1.40.0-haf1e3a3_0
  pytorch            pytorch/osx-64::pytorch-1.11.0-py3.7_0



pytorch-1.11.0       | 69.7 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transact

In [44]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
 
# Random initialization
torch.manual_seed(0)
 
# input x, teacher t
data = [[1,1],[1,0],[0,1],[0,0]]
label = [[1,0],[0,1],[0,1],[1,0]]
x = torch.tensor(data, dtype=torch.float32)
y = torch.tensor(label, dtype=torch.float32) 
print("x=",x)
print("y=",y)
 
# dataset
dataset = TensorDataset(x,y)
# data loader
train = dataset
batch_size = 1 # mini batch size
train_loader = DataLoader(train, batch_size, shuffle=True)
 
# My Neural Network
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        mid = 2 # mid layer
        # input:2 mid:2
        self.fc1 = nn.Linear(2,mid)
        # mid:2 output:1
        self.fc2 = nn.Linear(mid,2)
 
    def forward(self, x):
        x = self.fc1(x)
        x = torch.sigmoid(x)
        x = self.fc2(x)
        return x
# new
net = Net()
 
# Loss function
criterion = nn.MSELoss(reduction="sum")
 
# Stochastic gradient descent
optimizer = torch.optim.SGD(net.parameters(), lr=0.1)
 
# Train
print("+++TRAIN+++")
max_epoch=2000
for epoch in range(max_epoch+1) :
    for batch in train_loader:
        x,y = batch
        #clear grad
        optimizer.zero_grad() 
        #forward
        pred=net(x)
        #loss function
        loss = criterion(pred,y)
        #BP
        loss.backward()
        #update
        optimizer.step()
    if epoch % 500 == 0:
        print("epoc:", epoch, ' loss:', loss.item())

# Test
print("+++Test+++")
net.eval()
with torch.no_grad() :
    x = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
    y = net(x)
    y_label = torch.argmax(y, dim=1)
    for x_, y in zip(x, y_label):
        print('input:{}, output:{}'.format(x_, y.item()))

x= tensor([[1., 1.],
        [1., 0.],
        [0., 1.],
        [0., 0.]])
y= tensor([[1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
+++TRAIN+++
epoc: 0  loss: 0.6789630651473999
epoc: 500  loss: 0.04436979442834854
epoc: 1000  loss: 1.3847284208168276e-08
epoc: 1500  loss: 1.2079226507921703e-12
epoc: 2000  loss: 1.4566126083082054e-13
+++Test+++
input:tensor([0., 0.]), output:0
input:tensor([0., 1.]), output:1
input:tensor([1., 0.]), output:1
input:tensor([1., 1.]), output:0


tensor([0., 0.]) 0
tensor([0., 1.]) 1
tensor([1., 0.]) 1
tensor([1., 1.]) 0


In [38]:
list(x_)

[tensor(0.), tensor(0.)]

In [22]:
y_label = torch.argmax(y)
y_label

tensor(0)

In [9]:
! conda install -y tensorflow

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/nakatani/.pyenv/versions/anaconda3-5.3.0/envs/m1

  added / updated specs:
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    absl-py-0.15.0             |     pyhd3eb1b0_0          98 KB
    astor-0.8.1                |   py37hecd8cb5_0          45 KB
    cached-property-1.5.2      |             py_0          11 KB
    dataclasses-0.8            |     pyh6d0b6a4_7           7 KB
    gast-0.2.2                 |           py37_0         137 KB
    google-pasta-0.2.0         |     pyhd3eb1b0_0          43 KB
    grpcio-1.42.0              |   py37ha29bfda_0         1.9 MB
    h5py-3.6.0                 |   py37h4a1dd59

In [4]:
import numpy as np
from keras.models import Sequential, model_from_json
from keras.layers.core import Dense
from keras.optimizers import RMSprop

def main():
    # 訓練データの用意
    # 入力データ
    x_train = np.array([[0.0, 0.0],
                        [1.0, 0.0],
                        [0.0, 1.0],
                        [1.0, 1.0]])
    # 入力の教師データ
    y_train = np.array([0.0, 1.0, 1.0, 0.0])

    # モデル構築
    model = Sequential()
    # 入力層
    model.add(Dense(2, activation='sigmoid', input_shape=(2,)))
    # 出力層
    model.add(Dense(1, activation='linear'))
    # コンパイル（勾配法：RMSprop、損失関数：mean_squared_error、評価関数：accuracy）
    model.compile(loss='mean_squared_error', optimizer=RMSprop(), metrics=['accuracy'])
    # 構築したモデルで学習
    history = model.fit(x_train, y_train, batch_size=4, epochs=30)

    # テストデータの用意
    x_test = x_train
    y_test = y_train
       
    # モデルの性能評価
    score = model.evaluate(x_train, y_train, verbose=0)
    print('Score:', score[0])    # Score: 3.55525435225e-06
    print('Accuracy:', score[1]) # Accuracy: 1.0

    # 学習済みモデルを使って答えを予測
    x = np.array([[0, 1]])
    y = model.predict(x)
    print(y) # [[ 1.00200975]]

[Pytorchで機械学習２：XOR問題の学習](http://techno-road.com/blog/?content=7#xor1_src)

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np
import matplotlib.pyplot as plt